name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Test and Coverage
        run: npm run coverage

      - name: Convert to Summary File
        run: node convert-coverage.js

      - name: Run Coverage Badge Action
        uses: we-cli/coverage-badge-action@main
        with:
          # Specify the correct path to the coverage summary file
          coverage-summary: './coverage/coverage-summary.json'
  

      # Add this
      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main

      - name: Build
        run: npm run build

      - name: List Contents
        run: ls -R

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.NEWS_APP_IVN_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
