name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          git checkout main
          npm run build
        env:
          CI: false

      - name: List Build Directory Contents
        run: ls -R build

deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout gh-pages Branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Copy Build Artifacts
      run: |
        cp -r ${{ github.workspace }}/build/* .
        ls -R

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
